name: Continuous Integration

"on":
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    continuous_integration:
        runs-on: ubuntu-slim

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Vite+
              uses: voidzero-dev/setup-vp@v1.20.0
              with:
                  cache: true

            - name: Install Dependencies
              run: vp install

            - name: Code Checks
              run: vp check

            - name: Run Tests
              run: vp test

            - name: Build Application
              run: vp build
